name: Vault
main: net.milkbowl.vault.Vault
version: 1.1.1dev-b000
author: Cereal
description: >
             Abstraction Library for Bukkit Plugins
commands:
  vault-info:
    description: Displays information about Vault 
    usage: |
           /<command> - Displays Vault information
  vault-reload:
    description: Reloads Vault
    usage: |
           /<command> - Reloads Vault
