name: ${project.name}
version: ${project.version}-b${env.TRAVIS_BUILD_NUMBER}
description: ${project.description}
authors: [cereal, Sleaker, mung3r]
website: ${project.url}

main: ${mainClass}
load: startup

commands:
  vault-info:
    description: Displays information about Vault 
    usage: |
           /<command> - Displays Vault information
  vault-convert:
    description: Converts all data in economy1 and dumps it into economy2
    usage: |
           /<command> [economy1] [economy2]
permissions:
  vault.admin:
    description: Notifies the player when vault is in need of an update.
    default: op